version: "3.2"

services:

  mariadb:
    image: mariadb:10.3
    container_name: seat-mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${DB_USERNAME:-seat}
      MYSQL_PASSWORD: ${DB_PASSWORD:-deargodpleasedontlevethisblank}
      MYSQL_DATABASE: ${DB_DATABASE:-seat}
    volumes:
      - "mariadb-data:/var/lib/mysql"
    networks:
      - seat-network

  redis:
    image: redis:3
    container_name: seat-redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - "redis-data:/data"
    networks:
      - seat-network

  nginx:
    image: eveseat/eveseat-nginx
    depends_on:
      - seat-app
    container_name: seat-nginx
    restart: always
    environment:
      NGINX_HOST: ${NGINX_HOST:-_}
      VIRTUAL_HOST: ${VIRTUAL_HOST:-seat.localhost}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST:-seat.localhost}
    volumes:
      - "seat-code:/var/www/seat"
      # Remove the comment below to enable nginx logs to disk.
      #- ./logs/nginx/:/var/log/nginx/
    command: /bin/sh -c "envsubst '${NGINX_HOST}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    networks:
      - seat-network

  seat-app:
    image: eveseat/eveseat-app
    container_name: seat-app
    restart: always
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
      DB_USERNAME: ${DB_USERNAME:-seat}
      DB_PASSWORD: ${DB_PASSWORD:-deargodpleasedontlevethisblank}
      DB_DATABASE: ${DB_DATABASE:-seat}
      APP_DEBUG: ${APP_DEBUG:-false}
      EVE_CLIENT_ID: ${EVE_CLIENT_ID:-null}
      EVE_CLIENT_SECRET: ${EVE_CLIENT_SECRET:-null}
      EVE_CALLBACK_URL: ${EVE_CALLBACK_URL:-https://localhost/auth/eve/callback}
      MAIL_DRIVER: ${MAIL_DRIVER:-smtp}
      MAIL_HOST: ${MAIL_HOST:-smtp.mailtrap.io}
      MAIL_PORT: ${MAIL_PORT:-2525}
      MAIL_USERNAME: ${MAIL_USERNAME:-null}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-null}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-null}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-seat@localhost}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-seatAdmin}
      NGINX_HTTP: ${NGINX_HTTP:-8080}
      NGINX_HTTPS: ${NGINX_HTTPS:-8443}
      NGINX_HOST: ${NGINX_HOST:-_}
      SEAT_PLUGINS: ${SEAT_PLUGINS}
      
    volumes:
      - "seat-code:/var/www/seat"
      #- ./logs:/var/www/seat/storage/logs
    depends_on:
      - mariadb
      - redis
    networks:
      - seat-network

  seat-worker:
    image: eveseat/eveseat-worker
    container_name: seat-worker
    restart: always
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
      DB_USERNAME: ${DB_USERNAME:-seat}
      DB_PASSWORD: ${DB_PASSWORD:-deargodpleasedontlevethisblank}
      DB_DATABASE: ${DB_DATABASE:-seat}
    volumes:
      - "seat-code:/var/www/seat"
    depends_on:
      - seat-app
      - mariadb
      - redis
    networks:
      - seat-network

  seat-cron:
    image: eveseat/eveseat-cron
    container_name: seat-cron
    restart: always
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
      DB_USERNAME: ${DB_USERNAME:-seat}
      DB_PASSWORD: ${DB_PASSWORD:-deargodpleasedontlevethisblank}
      DB_DATABASE: ${DB_DATABASE:-seat}
    volumes:
      - "seat-code:/var/www/seat"
    depends_on:
      - seat-app # for the seat-code volume
      - mariadb
      - redis
    networks:
      - seat-network

volumes:
    seat-code:
    redis-data:
    mariadb-data:

networks:
    seat-network: